### PR TITLE
Updated default deno version to 0.20.0

### PR DESCRIPTION
**Pull request by lucacasonato**
Also some packages got updated.

### CODE REVIEW

**Comment by axetroy** [comment]
Sorry, I am late.

I found `node_modules` updated

For example `package.json` same fields changes, `node_modules/.bin` have been removed

If I run the command `npm install` again, can I still get the same `node_modules` directory?

**Comment by hayd** [comment]
It seems like a better default, if no deno-version is provided, would be to use the latest.
I think you can do this using:

https://github.com/denolib/setup-deno/blob/e8364b834cc10c6071d676f4c2e7f33ae32f05c7/node_modules/%40actions/tool-cache/lib/tool-cache.js#L372

**Comment by zhmushan** [comment]
I am preparing to refactor the code.

**Comment by axetroy** [comment]
Since #4 has been merged, I closed issue.

**Pull request closed without merging**
