### PR TITLE
Archive this repo

### PR DESCRIPTION
**Pull request by zhmushan**
Anyway, we need to guide users to switch to the official version

cc @axetroy @lucacasonato

### CODE REVIEW

**Review by axetroy — APPROVED** [review]
I agree with this.

Once @lucacasonato confirmed the official action is ready, then I will archive it

**Comment by JohannesRudolph** [comment]
Is there any link to an official action?

**Comment by npinochet** [comment]
> Is there any link to an official action?

Here it is, https://github.com/denoland/setup-deno, it was in the PR :)

**Comment by lucacasonato** [comment]
@axetroy The action should be ready. Thanks to everyone for maintaining this action up to now 🙏

**Pull request merged**
