### PR TITLE
use official versions file

### LINKED ISSUE #47: v3 roadmap
In these iterations

In addition to the BUG fix, there is another point is to getting versions information

Github Apis has a rate limit, So we can't get version information via it.

### ~v1~:

In this version, we created a `release.json` to mark which versions of deno

But its shortcomings are obvious

This file needs to be updated whenever Deno releases a new version

It is not automated

> v1 has been deprecated

### v2:

Currently reading [https://raw.githubusercontent.com/denoland/deno/master/Releases.md](https://raw.githubusercontent.com/denoland/deno/master/Releases.md) file

Because Deno updates this file every time it is released

So you can get all Deno versions

But this is not a solution

Because you don't know when this file will change rules or rename or delete

### v3:

So we need a more stable way to get versions information

EDIT:

We will use the [version file](https://raw.githubusercontent.com/denoland/deno_website2/master/versions.json) provided by the dneoland official, and the minimum supported Deno version is v1.0.0.

This version will be released on June 1, 2021, at the latest

### PR DESCRIPTION
**Pull request by zhmushan**
fixed #47, #58

### CODE REVIEW

**Comment by axetroy** [comment]
Great Job! 👍

and I found that `checksum` is missing in `npm run check` scripts.

I don’t remember when it disappeared, can you add it back?

**Comment by zhmushan** [comment]
@axetroy I think `checksum` should not be included in `check`, because we will only update `dist/index.js` when the new version is released.

**Comment by zhmushan** [comment]
But ci did an invalid check, I will fix it

**Review by axetroy — APPROVED** [review]
LGTM!

**Pull request merged**
