### PR TITLE
Use GitHub Releases API to fetch Deno versions

### PR DESCRIPTION
**Pull request by joshmgross**
Using the Releases API directly removes any dependency on a `Releases.md` file or any specific formatting for that file.

API Docs: https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

Verified latest changes: https://github.com/joshmgross/deno-testing/commit/9e824bfeee5c2a272e21d687f170f4447a012262/checks?check_suite_id=408901273

### CODE REVIEW

**Comment by joshmgross** [comment]
Ah, I see the issue. The GitHub API rate limit is 60 for unauthenticated requests, and that's based on the IP address of the machine, so it becomes a dice roll if the limit has been hit depending on which VM runs the build.

**Comment by axetroy** [comment]
Thanks for your PR.

You can watch this: https://github.com/denoland/deno_website2/pull/180

Once it land on. We can use the specific API at Github Action

**Comment by joshmgross** [comment]
@axetroy I've updated this to use the GitHub token available in workflows, this should avoid rate-limiting.

**Comment by axetroy** [comment]
@joshmgross 
We should not use Github Api for this.

Restrictions persist even if a personal token is set

This is not a way.

We should wait Deno official API land.

**Pull request closed without merging**
